CREATE DATABASE IF NOT EXISTS tulista CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tulista;

CREATE TABLE IF NOT EXISTS categorias (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS marcas (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS unidades_medida (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS productos (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    categoria_id INT UNSIGNED NOT NULL,
    nombre VARCHAR(200) NOT NULL,
    sku VARCHAR(100) DEFAULT NULL,
    marca_id INT UNSIGNED DEFAULT NULL,
    modelo VARCHAR(100) DEFAULT NULL,
    unidad_id INT UNSIGNED DEFAULT NULL,
    codigo_barras VARCHAR(100) DEFAULT NULL,
    tipo_item VARCHAR(100) DEFAULT NULL,
    costo_neto DECIMAL(12,2) NOT NULL DEFAULT 0,
    precio_venta_neto DECIMAL(12,2) NOT NULL DEFAULT 0,
    precio_venta_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    stock_minimo INT NOT NULL DEFAULT 0,
    comision_vendedor DECIMAL(8,2) NOT NULL DEFAULT 0,
    existencia INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id),
    CONSTRAINT fk_producto_marca FOREIGN KEY (marca_id) REFERENCES marcas(id),
    CONSTRAINT fk_producto_unidad FOREIGN KEY (unidad_id) REFERENCES unidades_medida(id)
);
