ALTER TABLE usuarios
    ADD COLUMN IF NOT EXISTS telefono VARCHAR(40) DEFAULT NULL AFTER email,
    ADD COLUMN IF NOT EXISTS direccion VARCHAR(255) DEFAULT NULL AFTER telefono,
    ADD COLUMN IF NOT EXISTS cargo VARCHAR(120) DEFAULT NULL AFTER direccion,
    ADD COLUMN IF NOT EXISTS notas VARCHAR(255) DEFAULT NULL AFTER cargo;
